// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const configDir = dirname(fileURLToPath(import.meta.url));
// Load .env from workspace root (two levels up from packages/database)
config({ path: resolve(configDir, "../../.env") });

export default defineConfig({
  schema: join(configDir, "prisma", "schema.prisma"),

  datasource: {
    url: process.env.DATABASE_URL!,
  },

  migrations: {
    path: join(configDir, "prisma", "migrations"),
  },
});
