// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const configDir = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  schema: join(configDir, "prisma", "schema.prisma"),
  migrations: {
    path: join(configDir, "prisma", "migrations"),
  },
  datasource: {
    url: "file:./pc-store.db",
  },
});
